// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpreadJsDemoApi;

namespace SpreadJsDemoApi.Migrations
{
    [DbContext(typeof(SpreadContext))]
    partial class SpreadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpreadJsDemoApi.GangJingAnZhuang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GangJingChangDuPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GangJingChangDuSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GangJingChangDuSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaoChengPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaoChengSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaoChengSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuJiaWaiJingPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuJiaWaiJingSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuJiaWaiJingSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouDuPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouDuSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouDuSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuJingPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuJingSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuJingSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableHeadId")
                        .HasColumnType("int");

                    b.Property<string>("ZhuJingJianJuPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZhuJingJianJuSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZhuJingJianJuSj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GangJingAnZhuang");
                });

            modelBuilder.Entity("SpreadJsDemoApi.PostionTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int>("ColCount")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("RowCount")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PostionTemp");
                });

            modelBuilder.Entity("SpreadJsDemoApi.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DtoNameSpace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstanceCount")
                        .HasColumnType("int");

                    b.Property<string>("TableDtoDataName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableDtoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNamespace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Relation");
                });

            modelBuilder.Entity("SpreadJsDemoApi.ShuiNiHunLingTu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BanHouDuPc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanHouDuSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanHouDuSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuanBanLv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaoChaSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GaoChaSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Other3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShenDuSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShenDuSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShunZhiDuSc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShunZhiDuSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableHeadId")
                        .HasColumnType("int");

                    b.Property<string>("XiShu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShuiNiHunLingTu");
                });

            modelBuilder.Entity("SpreadJsDemoApi.TableHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CBDW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContractNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JLDW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignRecord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkPart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TableHead");
                });
#pragma warning restore 612, 618
        }
    }
}
